#!/bin/bash

echo "Gray reordering ..."
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.mtx /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/cage12/cage12.mtx /mnt/nvme/dataset-spgemm/cage12/cage12.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/cage15/cage15.mtx /mnt/nvme/dataset-spgemm/cage15/cage15.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/cant/cant.mtx /mnt/nvme/dataset-spgemm/cant/cant.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.mtx /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/conf5_4-8x8-05/conf5_4-8x8-05.mtx /mnt/nvme/dataset-spgemm/conf5_4-8x8-05/conf5_4-8x8-05.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/consph/consph.mtx /mnt/nvme/dataset-spgemm/consph/consph.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.mtx /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/delaunay_n24/delaunay_n24.mtx /mnt/nvme/dataset-spgemm/delaunay_n24/delaunay_n24.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/filter3D/filter3D.mtx /mnt/nvme/dataset-spgemm/filter3D/filter3D.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.mtx /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/hood/hood.mtx /mnt/nvme/dataset-spgemm/hood/hood.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.mtx /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.mtx /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.mtx /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/majorbasis/majorbasis.mtx /mnt/nvme/dataset-spgemm/majorbasis/majorbasis.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/mario002/mario002.mtx /mnt/nvme/dataset-spgemm/mario002/mario002.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.mtx /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/mono_500Hz/mono_500Hz.mtx /mnt/nvme/dataset-spgemm/mono_500Hz/mono_500Hz.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/offshore/offshore.mtx /mnt/nvme/dataset-spgemm/offshore/offshore.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/patents_main/patents_main.mtx /mnt/nvme/dataset-spgemm/patents_main/patents_main.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/pdb1HYS/pdb1HYS.mtx /mnt/nvme/dataset-spgemm/pdb1HYS/pdb1HYS.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.mtx /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/pwtk/pwtk.mtx /mnt/nvme/dataset-spgemm/pwtk/pwtk.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/rma10/rma10.mtx /mnt/nvme/dataset-spgemm/rma10/rma10.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/scircuit/scircuit.mtx /mnt/nvme/dataset-spgemm/scircuit/scircuit.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/shipsec1/shipsec1.mtx /mnt/nvme/dataset-spgemm/shipsec1/shipsec1.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/wb-edu/wb-edu.mtx /mnt/nvme/dataset-spgemm/wb-edu/wb-edu.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.mtx /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.grayorder
###ISPASS-2023 datasets
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/333SP/333SP.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/333SP/333SP.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/adaptive/adaptive.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/adaptive/adaptive.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/af_shell10/af_shell10.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/af_shell10/af_shell10.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/AS365/AS365.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/AS365/AS365.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/as-Skitter/as-Skitter.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/as-Skitter/as-Skitter.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/channel-500x100x100-b050/channel-500x100x100-b050.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/channel-500x100x100-b050/channel-500x100x100-b050.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/circuit5M/circuit5M.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/circuit5M/circuit5M.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/cit-Patents/cit-Patents.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/cit-Patents/cit-Patents.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/com-LiveJournal/com-LiveJournal.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/com-LiveJournal/com-LiveJournal.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/com-Orkut/com-Orkut.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/com-Orkut/com-Orkut.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/CurlCurl_4/CurlCurl_4.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/CurlCurl_4/CurlCurl_4.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/europe_osm/europe_osm.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/europe_osm/europe_osm.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/G3_circuit/G3_circuit.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/G3_circuit/G3_circuit.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-road/GAP-road.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-road/GAP-road.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-twitter/GAP-twitter.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-twitter/GAP-twitter.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/hugebubbles-00020/hugebubbles-00020.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/hugebubbles-00020/hugebubbles-00020.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetrace-00020/hugetrace-00020.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetrace-00020/hugetrace-00020.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetric-00010/hugetric-00010.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetric-00010/hugetric-00010.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/HV15R/HV15R.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/HV15R/HV15R.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/kkt_power/kkt_power.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/kkt_power/kkt_power.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/kron_g500-logn21/kron_g500-logn21.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/kron_g500-logn21/kron_g500-logn21.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/M6/M6.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/M6/M6.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/mawi_201512020330/mawi_201512020330.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/mawi_201512020330/mawi_201512020330.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/nlpkkt240/nlpkkt240.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/nlpkkt240/nlpkkt240.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/NLR/NLR.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/NLR/NLR.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/packing-500x100x100-b050/packing-500x100x100-b050.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/packing-500x100x100-b050/packing-500x100x100-b050.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/patents/patents.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/patents/patents.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/Queen_4147/Queen_4147.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/Queen_4147/Queen_4147.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/rajat31/rajat31.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/rajat31/rajat31.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/rgg_n_2_24_s0/rgg_n_2_24_s0.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/rgg_n_2_24_s0/rgg_n_2_24_s0.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/sk-2005/sk-2005.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/sk-2005/sk-2005.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-LiveJournal1/soc-LiveJournal1.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-LiveJournal1/soc-LiveJournal1.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-Pokec/soc-Pokec.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-Pokec/soc-Pokec.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/stokes/stokes.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/stokes/stokes.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/sx-stackoverflow/sx-stackoverflow.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/sx-stackoverflow/sx-stackoverflow.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/venturiLevel3/venturiLevel3.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/venturiLevel3/venturiLevel3.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/wikipedia-20070206/wikipedia-20070206.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/wikipedia-20070206/wikipedia-20070206.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-Talk/wiki-Talk.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-Talk/wiki-Talk.grayorder
./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-topcats/wiki-topcats.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-topcats/wiki-topcats.grayorder

#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.mtx /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.mtx /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.mtx /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.mtx /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/mario002/mario002.mtx /mnt/nvme/dataset-spgemm/mario002/mario002.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.mtx /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/cage12/cage12.mtx /mnt/nvme/dataset-spgemm/cage12/cage12.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.mtx /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.mtx /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.mtx /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.mtx /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/pwtk/pwtk.mtx /mnt/nvme/dataset-spgemm/pwtk/pwtk.grayorder
#./build/examples/gray_order/gray_order /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.mtx /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.grayorder

echo "AMD reordering ..."
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.mtx /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/cage12/cage12.mtx /mnt/nvme/dataset-spgemm/cage12/cage12.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/cage15/cage15.mtx /mnt/nvme/dataset-spgemm/cage15/cage15.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/cant/cant.mtx /mnt/nvme/dataset-spgemm/cant/cant.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.mtx /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/conf5_4-8x8-05/conf5_4-8x8-05.mtx /mnt/nvme/dataset-spgemm/conf5_4-8x8-05/conf5_4-8x8-05.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/consph/consph.mtx /mnt/nvme/dataset-spgemm/consph/consph.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.mtx /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/delaunay_n24/delaunay_n24.mtx /mnt/nvme/dataset-spgemm/delaunay_n24/delaunay_n24.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/filter3D/filter3D.mtx /mnt/nvme/dataset-spgemm/filter3D/filter3D.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.mtx /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/hood/hood.mtx /mnt/nvme/dataset-spgemm/hood/hood.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.mtx /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.mtx /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.mtx /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/majorbasis/majorbasis.mtx /mnt/nvme/dataset-spgemm/majorbasis/majorbasis.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/mario002/mario002.mtx /mnt/nvme/dataset-spgemm/mario002/mario002.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.mtx /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/mono_500Hz/mono_500Hz.mtx /mnt/nvme/dataset-spgemm/mono_500Hz/mono_500Hz.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/offshore/offshore.mtx /mnt/nvme/dataset-spgemm/offshore/offshore.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/patents_main/patents_main.mtx /mnt/nvme/dataset-spgemm/patents_main/patents_main.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/pdb1HYS/pdb1HYS.mtx /mnt/nvme/dataset-spgemm/pdb1HYS/pdb1HYS.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.mtx /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/pwtk/pwtk.mtx /mnt/nvme/dataset-spgemm/pwtk/pwtk.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/rma10/rma10.mtx /mnt/nvme/dataset-spgemm/rma10/rma10.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/scircuit/scircuit.mtx /mnt/nvme/dataset-spgemm/scircuit/scircuit.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/shipsec1/shipsec1.mtx /mnt/nvme/dataset-spgemm/shipsec1/shipsec1.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/wb-edu/wb-edu.mtx /mnt/nvme/dataset-spgemm/wb-edu/wb-edu.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.mtx /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.amdorder
###ISPASS-2023 datasets
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/333SP/333SP.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/333SP/333SP.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/adaptive/adaptive.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/adaptive/adaptive.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/af_shell10/af_shell10.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/af_shell10/af_shell10.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/AS365/AS365.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/AS365/AS365.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/as-Skitter/as-Skitter.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/as-Skitter/as-Skitter.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/channel-500x100x100-b050/channel-500x100x100-b050.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/channel-500x100x100-b050/channel-500x100x100-b050.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/circuit5M/circuit5M.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/circuit5M/circuit5M.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/cit-Patents/cit-Patents.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/cit-Patents/cit-Patents.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/com-LiveJournal/com-LiveJournal.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/com-LiveJournal/com-LiveJournal.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/com-Orkut/com-Orkut.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/com-Orkut/com-Orkut.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/CurlCurl_4/CurlCurl_4.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/CurlCurl_4/CurlCurl_4.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/europe_osm/europe_osm.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/europe_osm/europe_osm.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/G3_circuit/G3_circuit.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/G3_circuit/G3_circuit.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-road/GAP-road.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-road/GAP-road.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-twitter/GAP-twitter.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/GAP-twitter/GAP-twitter.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/hugebubbles-00020/hugebubbles-00020.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/hugebubbles-00020/hugebubbles-00020.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetrace-00020/hugetrace-00020.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetrace-00020/hugetrace-00020.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetric-00010/hugetric-00010.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/hugetric-00010/hugetric-00010.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/HV15R/HV15R.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/HV15R/HV15R.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/kkt_power/kkt_power.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/kkt_power/kkt_power.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/kron_g500-logn21/kron_g500-logn21.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/kron_g500-logn21/kron_g500-logn21.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/M6/M6.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/M6/M6.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/mawi_201512020330/mawi_201512020330.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/mawi_201512020330/mawi_201512020330.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/nlpkkt240/nlpkkt240.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/nlpkkt240/nlpkkt240.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/NLR/NLR.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/NLR/NLR.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/packing-500x100x100-b050/packing-500x100x100-b050.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/packing-500x100x100-b050/packing-500x100x100-b050.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/patents/patents.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/patents/patents.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/Queen_4147/Queen_4147.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/Queen_4147/Queen_4147.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/rajat31/rajat31.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/rajat31/rajat31.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/rgg_n_2_24_s0/rgg_n_2_24_s0.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/rgg_n_2_24_s0/rgg_n_2_24_s0.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/sk-2005/sk-2005.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/sk-2005/sk-2005.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-LiveJournal1/soc-LiveJournal1.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-LiveJournal1/soc-LiveJournal1.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-Pokec/soc-Pokec.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/soc-Pokec/soc-Pokec.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/stokes/stokes.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/stokes/stokes.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/sx-stackoverflow/sx-stackoverflow.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/sx-stackoverflow/sx-stackoverflow.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/venturiLevel3/venturiLevel3.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/venturiLevel3/venturiLevel3.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/wikipedia-20070206/wikipedia-20070206.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/wikipedia-20070206/wikipedia-20070206.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-Talk/wiki-Talk.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-Talk/wiki-Talk.amdorder
./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-topcats/wiki-topcats.mtx /mnt/nvme/dataset-spgemm/ISPASS-2023/wiki-topcats/wiki-topcats.amdorder

#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.mtx /mnt/nvme/dataset-spgemm/2cubes_sphere/2cubes_sphere.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.mtx /mnt/nvme/dataset-spgemm/com-Amazon/com-Amazon.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.mtx /mnt/nvme/dataset-spgemm/Freescale2/Freescale2.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.mtx /mnt/nvme/dataset-spgemm/m133-b3/m133-b3.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/mario002/mario002.mtx /mnt/nvme/dataset-spgemm/mario002/mario002.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.mtx /mnt/nvme/dataset-spgemm/poisson3Da/poisson3Da.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/cage12/cage12.mtx /mnt/nvme/dataset-spgemm/cage12/cage12.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.mtx /mnt/nvme/dataset-spgemm/cop20k_A/cop20k_A.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.mtx /mnt/nvme/dataset-spgemm/kmer_V1r/kmer_V1r.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.mtx /mnt/nvme/dataset-spgemm/mac_econ_fwd500/mac_econ_fwd500.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.mtx /mnt/nvme/dataset-spgemm/mc2depi/mc2depi.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/pwtk/pwtk.mtx /mnt/nvme/dataset-spgemm/pwtk/pwtk.amdorder
#./build/examples/amd_order/amd_order /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.mtx /mnt/nvme/dataset-spgemm/webbase-1M/webbase-1M.amdorder